// Palette ids are persisted by the backend.
// Changing an existing id remaps historic art unless the stored pixel data is migrated first.
export const PIXEL_PALETTE = [
  { id: 0, hex: "#000000", name: "Black" },
  { id: 1, hex: "#3c3c3c", name: "Dark Gray" },
  { id: 2, hex: "#787878", name: "Gray" },
  { id: 3, hex: "#d2d2d2", name: "Light Gray" },
  { id: 4, hex: "#ffffff", name: "White" },
  { id: 5, hex: "#600018", name: "Deep Red" },
  { id: 6, hex: "#ed1c24", name: "Red" },
  { id: 7, hex: "#ff7f27", name: "Orange" },
  { id: 8, hex: "#f6aa09", name: "Gold" },
  { id: 9, hex: "#f9dd3b", name: "Yellow" },
  { id: 10, hex: "#fffabc", name: "Light Yellow" },
  { id: 11, hex: "#0eb968", name: "Dark Green" },
  { id: 12, hex: "#13e67b", name: "Green" },
  { id: 13, hex: "#87ff5e", name: "Light Green" },
  { id: 14, hex: "#0c816e", name: "Dark Teal" },
  { id: 15, hex: "#10ae82", name: "Teal" },
  { id: 16, hex: "#13e1be", name: "Light Teal" },
  { id: 17, hex: "#60f7f2", name: "Cyan" },
  { id: 18, hex: "#28509e", name: "Dark Blue" },
  { id: 19, hex: "#4093e4", name: "Blue" },
  { id: 20, hex: "#6b50f6", name: "Indigo" },
  { id: 21, hex: "#99b1fb", name: "Light Indigo" },
  { id: 22, hex: "#780c99", name: "Dark Purple" },
  { id: 23, hex: "#aa38b9", name: "Purple" },
  { id: 24, hex: "#e09ff9", name: "Light Purple" },
  { id: 25, hex: "#cb007a", name: "Dark Pink" },
  { id: 26, hex: "#ec1f80", name: "Pink" },
  { id: 27, hex: "#f38da9", name: "Light Pink" },
  { id: 28, hex: "#684634", name: "Dark Brown" },
  { id: 29, hex: "#95682a", name: "Brown" },
  { id: 30, hex: "#f8b277", name: "Beige" },
  { id: 31, hex: "transparent", name: "Transparent" },
] as const;

export const PIXEL_PALETTE_DISPLAY_ROWS = [
  [
    PIXEL_PALETTE[0],
    PIXEL_PALETTE[1],
    PIXEL_PALETTE[2],
    PIXEL_PALETTE[3],
    PIXEL_PALETTE[4],
    PIXEL_PALETTE[28],
    PIXEL_PALETTE[29],
    PIXEL_PALETTE[30],
  ],
  [
    PIXEL_PALETTE[5],
    PIXEL_PALETTE[6],
    PIXEL_PALETTE[25],
    PIXEL_PALETTE[26],
    PIXEL_PALETTE[27],
    PIXEL_PALETTE[7],
    PIXEL_PALETTE[8],
    PIXEL_PALETTE[9],
  ],
  [
    PIXEL_PALETTE[10],
    PIXEL_PALETTE[11],
    PIXEL_PALETTE[12],
    PIXEL_PALETTE[13],
    PIXEL_PALETTE[14],
    PIXEL_PALETTE[15],
    PIXEL_PALETTE[16],
    PIXEL_PALETTE[17],
  ],
  [
    PIXEL_PALETTE[18],
    PIXEL_PALETTE[19],
    PIXEL_PALETTE[20],
    PIXEL_PALETTE[21],
    PIXEL_PALETTE[22],
    PIXEL_PALETTE[23],
    PIXEL_PALETTE[24],
    PIXEL_PALETTE[31],
  ],
] as const;

export const DEFAULT_COLOR_ID = 6;
